version: '3.8'

services:
  wallet-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ENV_FILE=/app/config.env
    volumes:
      - .:/app
    depends_on:
      - wallet-db
    # command: [go run main.go]
  
  wallet-db:
    image: postgres:15-alpine     
    environment:
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - POSTGRES_PASSWORD=12345
            - PGPORT=5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres 12345"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: