version: '3.8'

services:
  wallet-app:
    build: 
        context: .
    environment:
      - valet    
    ports:
      - "8080:8080"
    depends_on:
      - wallet-db

  
  wallet-db:
    container_name: valet
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data  
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U {POSTGRES_USER} -d postgres {POSTGRES_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: